# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59eae5404fb5d280a11ed5ee18f9e0fec7dc9fddcecff2efe2f21cce50d33127ea2948da674d145ca6db8fb9e1f1157249da02e96938372a1bcc1df967689d7b

test:
  secret_key_base: b248003d13bb140c63f74a16f72c9e10f0a569ca9d0a8fa0ca901153b21ee3670e3c3b821eb9f10049146b0c2be7c06cd83a7fa6b60e4d686e437a8cb58e7690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
